// Typelizer digest 56d74a16684f0b0443fc979cc8e3a52d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { User } from './'

type Account = User & {
  email: string
  time_zone: string
  social_login: boolean
}

export default Account
