// Typelizer digest 59041f9596b0126ab45f0ce780396584
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { Comment, FrameListItem } from './'

type FrameDetail = FrameListItem & {
  comment: string | null
  shooted_at: string
  created_at: string
  updated_at: string
  comments: Comment[]
}

export default FrameDetail
