// Typelizer digest 9ecc3894f45a582053957a43e2d3343b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface FrameListItem {
  id: number
  user_id: number
  user_name: string
  name: string
  creator_name: string | null
  private: boolean
  tag_list: string | null
  file_url: string
  file_two_url: string
  file_three_url: string
  file_six_url: string
}

export default FrameListItem
