// Typelizer digest 38158a03957a4f6f7211f6c897c5e82a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number
  name: string
  profile: string | null
  image_thumb_url: string
  image_one_url: string
  image_three_url: string
}

export default User
