google:
  client_id: <%= ENV.fetch('GOOGLE_CLIENT_ID') { '' } %>
  client_secret: <%= ENV.fetch('GOOGLE_CLIENT_SECRET') { '' } %>
origin: <%= ENV.fetch('BACKEND_ORIGIN_URL') { 'http://localhost:3000' } %>
frontend:
  origin: <%= ENV.fetch('FRONTEND_ORIGIN_URL') { 'http://localhost:3030' } %>
reverse_proxy:
  origin: <%= ENV.fetch('REVERSE_PROXY_ORIGIN_URL') { 'http://localhost' } %>
