origin: 'http://localhost:3000'
api:
  origin: 'http://localhost:3030'
front:
  api:
    origin: 'http://localhost:3000/api/front/v1'
sorcery:
  google_callback_url: 'http://localhost:3000/oauth/callback?provider=google'